### PR TITLE
Feature command pattern

### PR DESCRIPTION
**Pull request by ymte**

### CODE REVIEW

**Comment by ashay123** [comment]
Looks good, except for tags

**Comment by ymte** [comment]
fixes #105

**Comment by Tclv** [comment]
Noticed a lot flashing enemies on the border, that I did not notice on other branches. Any clue as to what is happening there?

**Comment by ymte** [comment]
Yes, this is caused by buffering the commands each frame and executing them at once. Will have a look into it.


Verstuurd door Outlook voor Android





On Sat, Oct 24, 2015 at 10:01 AM -0700, "Dorus Leliveld" <notifications@github.com> wrote:
Noticed a lot flashing enemies on the border, that I did not notice on other branches. Any clue as to what is happening there?

---

**Comment by ymte** [comment]
Okay fixed; it was happening because the bounds of the enemies were not directly set at start.

**Comment by ashay123** [comment]
Check it out, and looks good to me, merged.

**Pull request merged**
