### PR TITLE
Feature settings keys movement <organisation, testing

### PR DESCRIPTION
**Pull request by Tclv**
Settings now holds the keybinds to the game. These are saved and loaded at start. There's an interface for setting and getting the keybindings for the various controllers.
<organisation, testing

### CODE REVIEW

**Comment by Tclv** [comment]
Apparently this build fails on travis, which caught me by surprise because I can not reproduce me on my machine (at least not with `mvn clean` or anything along those lines). Looking into travis error dump right now.

**Comment by Tclv** [comment]
Should be fixed now. Not sure why merging development branch into this fixed it, bug on travis' end?

**Comment by jonascarpay** [comment]
Great, please merge

**Comment by ashay123** [comment]
Great feature, merged.

**Pull request merged**
