### PR TITLE
Fixed the field test <testing

### LINKED ISSUE #116: Fieldtest test fix

### PR DESCRIPTION
**Pull request by Tclv**
Fixed the commented out test in `FieldTest` fixes #116.
<testing

### CODE REVIEW

**Comment by ymte** [comment]
increases code coverage; solid and robust test.

**Comment by ashay123** [comment]
Great, could not fix this. Maybe more descriptive variable name for EnemyIterator?

**Comment by Tclv** [comment]
Sure I'll patch that one in @ashay123.

**Comment by ashay123** [comment]
Nice, I'll merge it.

**Pull request merged**
