### PR TITLE
Feature renderer unit tests

### PR DESCRIPTION
**Pull request by Tclv**
Wrote unit tests for renderer class
<testing

### CODE REVIEW

**Comment by jonascarpay** [comment]
looks good[ERROR] /Users/jmc/Dev/SEM_46/core/src/test/java/com/sem46/RendererTest.java:[18,27] error: cannot find symbol
[ERROR]   symbol:   class Gl
  location: class Gdx
/Users/jmc/Dev/SEM_46/core/src/test/java/com/sem46/RendererTest.java:[45,8] error: cannot find symbol
[ERROR]   symbol:   class Gl
  location: class RendererTest
/Users/jmc/Dev/SEM_46/core/src/test/java/com/sem46/RendererTest.java:[45,21] error: cannot find symbol

**Comment by jonascarpay** [comment]
Looks good. How much code coverage do we have after this pull?

**Comment by Tclv** [comment]
56%

**Comment by ashay123** [comment]
Excellent, merged.

**Pull request merged**
