### PR TITLE
add upper limit to command history, fix #120 < bug

### LINKED ISSUE #120: Upper limit no commands saved

### PR DESCRIPTION
**Pull request by ymte**

### CODE REVIEW

**Comment by ashay123** [comment]
Good preventing of OutOfMemoryException

**Comment by Tclv** [comment]
why `60 * 3600 = 216 000`? Isn't that still on the large side? What's the size of a single command object. It seems silly to keep close to a GB of commands in memory.

**Comment by ymte** [comment]
I don't know the size exactly; 60 * 3600 is one hour; when one command object is 1kb this is 216MB. Can set it lower, to five minutes for example.

**Comment by Tclv** [comment]
Makes sense, can't think of a situation where rewiniding the game for more than a few minutes at most would happen.

**Comment by ymte** [comment]
Okay, limit changed to five minutes.

**Pull request merged**
