### PR TITLE
fix #113: better rotation depending on velocity < logic, feature

### LINKED ISSUE #113: smoother fish rotation when not accelerating

### PR DESCRIPTION
**Pull request by ymte**

### CODE REVIEW

**Comment by ashay123** [comment]
Not much to say.

**Comment by Tclv** [comment]
Seems like a very complex system. Is there any reason why the fish wouldn't follow the same direction the velocity vector?

**Comment by ymte** [comment]
Personally I think it feels better; this is a matter of taste. Also the fish' direction won't vary as much anymore when you are going up very slowly then pressing down. I can simplify/extend the code some more if the system seems too complex, or revert this if this feature is undesirable.

**Comment by Tclv** [comment]
Sounds okay, you gave it more thought than I did at least. Somehow I can still moonwalk, but I don't necessarily mind that. @jonascarpay what do you think?

**Comment by jonascarpay** [comment]
I suppose it's better than before

**Pull request merged**
