### PR TITLE
#Organisation

### PR DESCRIPTION
**Pull request by JorisBelier**
This code decouples the responsibility of observing GameObject
collisions among several classes.

### CODE REVIEW

**Comment by ashay123** [comment]
Checkstyle violations causing build failure <bug

**Comment by Tclv** [comment]
Ik mis ook de testen

**Comment by ashay123** [comment]
Good fix

**Comment by ashay123** [comment]
Everything look fine, except for the commented out test-method in FieldTest, be sure to fix this afterwards.

**Pull request merged**
